// ==============================================================================
// P-256 SCALAR REFERENCE IMPLEMENTATION - GOLDEN FROZEN VERSION
// ==============================================================================
// ⚠️  DO NOT EDIT THIS FILE ⚠️
//
// This is the GOLDEN REFERENCE implementation, frozen on 2025-11-29.
// All other implementations must be tested against THIS as ground truth.
//
// Purpose: Scalar field operations and Jacobian arithmetic (reference only)
// Used by: Test suite for validation
// Status: FROZEN - Any changes require full regression test suite
//
// If you need to optimize/modify:
//   1. Create a new file (e.g., p256_scalar_ref_fast.cuh)
//   2. Add tests comparing new version against THIS golden ref
//   3. Never modify this file directly
// ==============================================================================

#ifndef P256_SCALAR_REF_CUH
#define P256_SCALAR_REF_CUH

#include <stdint.h>

// ==============================================================================
// Constants - Copied EXACTLY from p256_sign_persistent_reference.cu
// ==============================================================================
// These are the REFERENCE values - do not modify!
// Verified against NIST P-256 specification.

#ifndef P256_SCALAR_CONSTANTS_DEFINED
#define P256_SCALAR_CONSTANTS_DEFINED

// 256-bit prime for NIST P-256 in 8x32-bit little endian
static __device__ __constant__ uint32_t P256_P[8] = {
    0xffffffffu, 0xffffffffu, 0xffffffffu, 0x00000000u,
    0x00000000u, 0x00000000u, 0x00000001u, 0xffffffffu
};

// R^2 mod p for Montgomery (2^512 mod p)
static __device__ __constant__ uint32_t P256_R2[8] = {
    0x00000003u,
    0x00000000u,
    0xffffffffu,
    0xfffffffbu,
    0xfffffffeu,
    0xffffffffu,
    0xfffffffdu,
    0x00000004u
};

// Base point Gx, Gy in 8x32-bit little endian
static __device__ __constant__ uint32_t P256_GX[8] = {
    0xd898c296u, 0xf4a13945u, 0x2deb33a0u, 0x77037d81u,
    0x63a440f2u, 0xf8bce6e5u, 0xe12c4247u, 0x6b17d1f2u
};

static __device__ __constant__ uint32_t P256_GY[8] = {
    0x37bf51f5u, 0xcbb64068u, 0x6b315eceu, 0x2bce3357u,
    0x7c0f9e16u, 0x8ee7eb4au, 0xfe1a7f9bu, 0x4fe342e2u
};

#endif // P256_SCALAR_CONSTANTS_DEFINED

// ==============================================================================
// Helper Functions
// ==============================================================================

// n' = -p^{-1} mod 2^32 for least significant limb of p
__device__ __forceinline__ uint32_t mont_inv32_p_scalar() {
    // For p0 = 0xffffffff, the modular inverse is -1 mod 2^32 = 1
    return 0x00000001u;
}

__device__ __forceinline__ void fe_copy_scalar(uint32_t r[8], const uint32_t a[8]) {
    #pragma unroll
    for (int i = 0; i < 8; ++i) r[i] = a[i];
}

__device__ __forceinline__ int fe_cmp_scalar(const uint32_t a[8], const uint32_t b[8]) {
    for (int i = 7; i >= 0; --i) {
        if (a[i] < b[i]) return -1;
        if (a[i] > b[i]) return 1;
    }
    return 0;
}

// ==============================================================================
// Field Operations (Modular Arithmetic)
// ==============================================================================

// r = a - b (mod p), assumes a,b < 2p
__device__ __forceinline__ void fe_sub_scalar(uint32_t r[8], const uint32_t a[8], const uint32_t b[8]) {
    uint64_t borrow = 0;
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
        uint64_t diff = (uint64_t)a[i] - (uint64_t)b[i] - borrow;
        r[i]   = (uint32_t)diff;
        borrow = (diff >> 63) & 1;
    }
    if (borrow) {
        // add p back
        uint64_t carry = 0;
        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            uint64_t sum = (uint64_t)r[i] + (uint64_t)P256_P[i] + carry;
            r[i]   = (uint32_t)sum;
            carry  = sum >> 32;
        }
    }
}

// r = a + b (mod p), assumes a,b < p
__device__ __forceinline__ void fe_add_scalar(uint32_t r[8], const uint32_t a[8], const uint32_t b[8]) {
    uint64_t carry = 0;
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
        uint64_t sum = (uint64_t)a[i] + (uint64_t)b[i] + carry;
        r[i]   = (uint32_t)sum;
        carry  = sum >> 32;
    }
    // conditional subtract p
    if (carry || fe_cmp_scalar(r, P256_P) >= 0) {
        uint64_t borrow = 0;
        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            uint64_t diff = (uint64_t)r[i] - (uint64_t)P256_P[i] - borrow;
            r[i]   = (uint32_t)diff;
            borrow = (diff >> 63) & 1;
        }
    }
}

// r = a * b * R^{-1} mod p (CIOS Montgomery multiply)
__device__ __forceinline__ void mont_mul_scalar(uint32_t r[8], const uint32_t a[8], const uint32_t b[8]) {
    uint64_t t[17] = {0};  // FIX: Increased from 16 to 17 to catch overflow

    // schoolbook multiply
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
        uint64_t carry = 0;
        #pragma unroll
        for (int j = 0; j < 8; ++j) {
            uint64_t uv = t[i + j] + (uint64_t)a[j] * (uint64_t)b[i] + carry;
            t[i + j] = (uint32_t)uv;
            carry    = uv >> 32;
        }
        // FIX: Propagate schoolbook carry with overflow handling
        uint64_t acc_sb = t[i + 8] + carry;
        t[i + 8] = (uint32_t)acc_sb;
        uint64_t carry_sb = acc_sb >> 32;
        t[i + 9] += carry_sb;  // Safe: t has size 17
    }

    // CIOS reduction
    const uint32_t m0 = mont_inv32_p_scalar();
    for (int i = 0; i < 8; ++i) {
        uint32_t m = (uint32_t)t[i] * m0;
        uint64_t carry = 0;
        #pragma unroll
        for (int j = 0; j < 8; ++j) {
            uint64_t uv = t[i + j]
                        + (uint64_t)m * (uint64_t)P256_P[j]
                        + carry;
            t[i + j] = (uint32_t)uv;
            carry    = uv >> 32;
        }
        // FIX: Propagate carry to next limb instead of discarding high bits
        uint64_t acc = t[i + 8] + carry;
        t[i + 8] = (uint32_t)acc;
        uint64_t carry2 = acc >> 32;
        t[i + 9] += carry2;  // Safe: t now has size 17
    }

    // take high 8 limbs
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
        r[i] = (uint32_t)t[i + 8];
    }

    // FIX: Check t[16] for final overflow! CIOS can produce results up to 2*P.
    // If t[16] != 0, result is definitely >= P and we must subtract.
    uint32_t final_carry = (uint32_t)t[16];
    bool needs_subtract = (final_carry != 0) || (fe_cmp_scalar(r, P256_P) >= 0);

    // final conditional subtract
    if (needs_subtract) {
        uint64_t borrow = 0;
        #pragma unroll
        for (int i = 0; i < 8; ++i) {
            uint64_t diff = (uint64_t)r[i] - (uint64_t)P256_P[i] - borrow;
            r[i]   = (uint32_t)diff;
            borrow = (diff >> 63) & 1;
        }
    }
}

// r = a * R^2 mod p  (enter Montgomery)
__device__ __forceinline__ void to_mont_scalar(uint32_t r[8], const uint32_t a[8]) {
    mont_mul_scalar(r, a, P256_R2);
}

// r = a * 1 mod p (leave Montgomery)
__device__ __forceinline__ void from_mont_scalar(uint32_t r[8], const uint32_t a[8]) {
    uint32_t one[8] = {1u,0u,0u,0u,0u,0u,0u,0u};
    mont_mul_scalar(r, a, one);
}

// ==============================================================================
// Montgomery Domain Wrappers
// ==============================================================================

__device__ __forceinline__ void fe_mont_add_scalar(uint32_t r[8], const uint32_t a[8], const uint32_t b[8]) {
    fe_add_scalar(r, a, b);
}

__device__ __forceinline__ void fe_mont_sub_scalar(uint32_t r[8], const uint32_t a[8], const uint32_t b[8]) {
    fe_sub_scalar(r, a, b);
}

__device__ __forceinline__ void fe_mont_mul_scalar(uint32_t r[8], const uint32_t a[8], const uint32_t b[8]) {
    mont_mul_scalar(r, a, b);
}

__device__ __forceinline__ void fe_mont_sqr_scalar(uint32_t r[8], const uint32_t a[8]) {
    mont_mul_scalar(r, a, a);
}

// ==============================================================================
// Jacobian Point Struct
// ==============================================================================

struct P256_Jacobian_Scalar {
    uint32_t X[8];
    uint32_t Y[8];
    uint32_t Z[8];
};

// ==============================================================================
// Jacobian Point Operations
// ==============================================================================

__device__ __forceinline__ void set_infinity_scalar(P256_Jacobian_Scalar &P) {
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
        P.X[i] = 0;
        P.Z[i] = 0;
    }
    P.Y[0] = 1;
    #pragma unroll
    for (int i = 1; i < 8; ++i) P.Y[i] = 0;
}

__device__ __forceinline__ void set_basepoint_scalar(P256_Jacobian_Scalar &P) {
    uint32_t x[8], y[8], one[8] = {1u,0u,0u,0u,0u,0u,0u,0u};
    #pragma unroll
    for (int i = 0; i < 8; ++i) {
        x[i] = P256_GX[i];
        y[i] = P256_GY[i];
    }
    to_mont_scalar(P.X, x);
    to_mont_scalar(P.Y, y);
    to_mont_scalar(P.Z, one); // Z = 1 in Montgomery
}

// Point doubling (a = -3 form) in Montgomery domain
__device__ void point_double_scalar(P256_Jacobian_Scalar &R, const P256_Jacobian_Scalar &P) {
    uint32_t S[8], M[8], T[8], U[8];

    // S = 4*X*Y^2
    fe_mont_sqr_scalar(T, P.Y);
    fe_mont_mul_scalar(S, P.X, T);
    fe_mont_add_scalar(S, S, S);
    fe_mont_add_scalar(S, S, S);

    // M = 3*(X^2 - Z^4) using identity: 3*(X-Z^2)*(X+Z^2)
    fe_mont_sqr_scalar(T, P.Z);     // T = Z^2 (T1 in dbl-2001-b)
    fe_mont_sub_scalar(U, P.X, T);  // U = X - Z^2 (T2 in dbl-2001-b)
    fe_mont_add_scalar(T, P.X, T);  // T = X + Z^2 (reuse T1)
    fe_mont_mul_scalar(M, U, T);    // M = (X-Z^2)*(X+Z^2) = X^2 - Z^4
    fe_mont_add_scalar(U, M, M);    // U = 2*(X^2-Z^4) (temp for 3x)
    fe_mont_add_scalar(M, U, M);    // M = 3*(X^2-Z^4) (dbl-2001-b formula)

    // X3 = M^2 - 2S
    fe_mont_sqr_scalar(R.X, M);
    fe_mont_add_scalar(T, S, S);
    fe_mont_sub_scalar(R.X, R.X, T);

    // Y3 = M*(S - X3) - 8*Y^4
    fe_mont_sub_scalar(T, S, R.X);
    fe_mont_mul_scalar(T, M, T);
    fe_mont_sqr_scalar(U, P.Y);
    fe_mont_sqr_scalar(U, U);
    fe_mont_add_scalar(U, U, U);
    fe_mont_add_scalar(U, U, U);
    fe_mont_add_scalar(U, U, U);
    fe_mont_sub_scalar(R.Y, T, U);

    // Z3 = 2*Y*Z
    fe_mont_mul_scalar(R.Z, P.Y, P.Z);
    fe_mont_add_scalar(R.Z, R.Z, R.Z);
}

// Mixed addition: Jacobian + affine (for ladder)
__device__ void point_add_mixed_scalar(P256_Jacobian_Scalar &R,
                                       const P256_Jacobian_Scalar &P,
                                       const uint32_t x2[8],
                                       const uint32_t y2[8]) {
    uint32_t Z1Z1[8], U2[8], S2[8];
    uint32_t H[8], I[8], J[8], rr[8], V[8];

    fe_mont_sqr_scalar(Z1Z1, P.Z);
    fe_mont_mul_scalar(U2, x2, Z1Z1);
    fe_mont_mul_scalar(S2, y2, Z1Z1);
    fe_mont_mul_scalar(S2, S2, P.Z);

    fe_mont_sub_scalar(H, U2, P.X);
    fe_mont_add_scalar(I, H, H);
    fe_mont_sqr_scalar(I, I);
    fe_mont_mul_scalar(J, H, I);
    fe_mont_sub_scalar(rr, S2, P.Y);
    fe_mont_add_scalar(rr, rr, rr);
    fe_mont_mul_scalar(V, P.X, I);

    fe_mont_sqr_scalar(R.X, rr);
    fe_mont_sub_scalar(R.X, R.X, J);
    fe_mont_sub_scalar(R.X, R.X, V);
    fe_mont_sub_scalar(R.X, R.X, V);

    fe_mont_sub_scalar(R.Y, V, R.X);
    fe_mont_mul_scalar(R.Y, R.Y, rr);
    fe_mont_mul_scalar(S2, P.Y, J);
    fe_mont_add_scalar(S2, S2, S2);
    fe_mont_sub_scalar(R.Y, R.Y, S2);

    fe_mont_add_scalar(R.Z, P.Z, H);
    fe_mont_sqr_scalar(R.Z, R.Z);
    fe_mont_sub_scalar(R.Z, R.Z, Z1Z1);
    fe_mont_sqr_scalar(S2, H);
    fe_mont_sub_scalar(R.Z, R.Z, S2);
}

#endif // P256_SCALAR_REF_CUH
